apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bisrat1/projectmanagement-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/projectdb"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: projectmanagement-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
