apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: MONGO_URI
              value:  "{{ .Values.backend.mongoUri }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: projectmanagement-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port:  {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: LoadBalancer
